name: Docker

on:
  # pull_request:
  #   branches: [ main ]
  push:
    tags: [ v1.* ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: ./docker/build_image.sh

      - name: Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./docker/publish_image.sh
