name: Stitch CI

on:
  # pull_request:
  #   branches: [ main ]
  push:
    tags: [ v1.* ]

defaults:
  run:
    working-directory: ./packages/stitch
    shell: bash

jobs:
  build-test:
    name: Build code and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        buildx: [ x64, arm64 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
          architecture: ${{ matrix.buildx }}
      - run: npm ci
      - run: npm run build_all
      - run: npm run test

  audit:
    name: NPM Audit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        buildx: [ x64, arm64 ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
          architecture: ${{ matrix.buildx }}
      - run: npm audit --prod
